# Generated by Django 3.2.13 on 2022-09-08 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pizza_order.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pizza_order', '0016_auto_20220902_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_Scheduled_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('task', models.CharField(max_length=150)),
            ],
        ),
        # migrations.CreateModel(
        #     name='Scheduled_Order',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('order_idd', models.CharField(blank=True, max_length=100)),
        #         ('date', models.DateTimeField()),
        #         ('total_amount', models.IntegerField(default=0)),
        #         ('is_payed', models.BooleanField(default=False)),
        #         ('is_delivered', models.BooleanField(default=False)),
        #         ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_order.address')),
        #         ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_order.shop')),
        #         ('status', models.ForeignKey(default=pizza_order.models.get_default_status, on_delete=django.db.models.deletion.CASCADE, to='pizza_order.status')),
        #         ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
        # #     ],
        # ),
    ]
