# Generated by Django 3.2.13 on 2022-09-09 06:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0018_auto_20220909_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 6, 58, 38, 733039, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order_scheduled_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza_order.order'),
        ),
    ]
