# Generated by Django 3.2.13 on 2022-09-22 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_order', '0019_auto_20220909_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
